apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-slave
  namespace: java-infra
  labels:
    name: mysql-slave
spec:
  replicas: 1
  selector:
    name: mysql-slave
  template:
    metadata:
      labels:
        name: mysql-slave
    spec:
      containers:
      - name: slave
        image: nacos/nacos-mysql-slave:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-slave-data
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_REPLICATION_USER
          value: 'nacos_ru'
        - name: MYSQL_REPLICATION_PASSWORD
          value: 'nacos_ru'
      nodeName: 10.10.1.12
      volumes:
        - hostPath:
            path: /data/k8s/java-infra/nacos-mysql-slave
            type: DirectoryOrCreate
          name: mysql-slave-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  namespace: java-infra
  labels:
    name: mysql-slave
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql-slave